export class HistoriasClinicasDataDev {
    static listaHistoriasClinicas: any[] = [
        {
            "id": 1,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de alergias leves a ciertos alimentos. Ha experimentado dolores de cabeza ocasionales.",
            "antecedentesFamiliares": "Padre con historial de diabetes tipo 2. Madre con hipertensión arterial.",
            "antecedentesGinecoobstetricos": "Mujer, G1P0A0, sin complicaciones en su embarazo previo.",
            "antecedentesNoPatologicos": "No fumador, consume alcohol ocasionalmente, practica ejercicio moderado.",
            "antecedentesPatologicos": "Alergia a la penicilina reportada.",
            "antecedentesPersonales": "Operado de apendicitis en 2015. Sin otras intervenciones quirúrgicas.",
            "diagnosticoPresuntivo": "Sinusitis aguda.",
            "diagnosticosDiferenciales": "Cefalea tensional, migraña.",
            "examenFisicoGeneral": "Paciente consciente y orientado en las tres esferas. Sin signos de focalización neurológica.",
            "examenFisicoEspecial": "Exploración de cabeza y cuello sin alteraciones. Pupilas isocóricas y reactivas.",
            "propuestaBasicaDeConducta": "Tratamiento sintomático con descongestionantes nasales y analgésicos. Seguimiento si persisten síntomas.",
            "tratamiento": "Paciente prescrito con ibuprofeno 400mg cada 8 horas por 3 días. Pseudoefedrina 60mg cada 12 horas por 5 días.",
            "createdAt": "2023-05-10T08:00:00Z",
            "updatedAt": "2023-05-15T09:15:00Z",
            "deletedAt": null,
            "idEspecialidad": 1,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 10,
            "nombreMedico": "Valeria Ruiz",
            "idPaciente": 1,
            "ciPropietario": "098324789",
            "pacientePropietario": "Juan Tellez"
        },
        {
            "id": 2,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de diabetes tipo 2 y hipertensión. Reporta dolor torácico ocasional.",
            "antecedentesFamiliares": "Madre con hipertensión. Padre con diabetes tipo 2.",
            "antecedentesGinecoobstetricos": "Mujer, G2P1A0, sin complicaciones en sus embarazos.",
            "antecedentesNoPatologicos": "Fumador social, consume alcohol ocasionalmente, actividad física irregular.",
            "antecedentesPatologicos": "Diabetes tipo 2 y presión arterial alta.",
            "antecedentesPersonales": "Sin cirugías previas.",
            "diagnosticoPresuntivo": "Angina de pecho.",
            "diagnosticosDiferenciales": "Infarto agudo de miocardio, reflujo gastroesofágico.",
            "examenFisicoGeneral": "Paciente alerta y orientado. Presión arterial ligeramente elevada.",
            "examenFisicoEspecial": "Exploración cardiaca revela ruidos normales. No hay dolor a la palpación torácica.",
            "propuestaBasicaDeConducta": "Tratamiento con nitratos y control de la hipertensión. Reevaluación si los síntomas persisten.",
            "tratamiento": "Nitroglicerina sublingual según necesidad. Losartán 50mg cada día.",
            "createdAt": "2023-06-12T10:00:00Z",
            "updatedAt": "2023-06-20T11:45:00Z",
            "deletedAt": null,
            "idEspecialidad": 2,
            "nombreEspecialidad": "Cardiología",
            "idMedico": 12,
            "nombreMedico": "Luis Fernández",
            "idPaciente": 2,
            "ciPropietario": "123456789",
            "pacientePropietario": "Ana Morales"
        },
        {
            "id": 3,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de asma y alergias estacionales. Reporta tos persistente y dificultad para respirar.",
            "antecedentesFamiliares": "Padre con asma. Madre con alergias estacionales.",
            "antecedentesGinecoobstetricos": "Mujer, G1P0A0, sin embarazos previos.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, realiza ejercicio en interiores.",
            "antecedentesPatologicos": "Asma bronquial controlada con medicación.",
            "antecedentesPersonales": "Operada de apendicitis en 2021.",
            "diagnosticoPresuntivo": "Exacerbación del asma.",
            "diagnosticosDiferenciales": "Bronquitis crónica, neumonía.",
            "examenFisicoGeneral": "Paciente con signos de dificultad respiratoria. Alerta y orientado.",
            "examenFisicoEspecial": "Exploración pulmonar revela sibilancias y respiración entrecortada.",
            "propuestaBasicaDeConducta": "Tratamiento con broncodilatadores y esteroides inhalados. Reevaluación si los síntomas no mejoran.",
            "tratamiento": "Salbutamol inhalado según necesidad. Beclometasona inhalada dos veces al día.",
            "createdAt": "2023-07-01T13:00:00Z",
            "updatedAt": "2023-07-05T14:30:00Z",
            "deletedAt": null,
            "idEspecialidad": 3,
            "nombreEspecialidad": "Neumología",
            "idMedico": 14,
            "nombreMedico": "María Gómez",
            "idPaciente": 3,
            "ciPropietario": "234567890",
            "pacientePropietario": "David López"
        },
        {
            "id": 4,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de colesterol alto y sobrepeso. Reporta fatiga y dolores en el pecho.",
            "antecedentesFamiliares": "Madre con colesterol alto. Padre con enfermedades cardíacas.",
            "antecedentesGinecoobstetricos": "Mujer, G2P1A1, con antecedentes de un aborto espontáneo.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, realiza ejercicio ligero.",
            "antecedentesPatologicos": "Hipercolesterolemia no controlada.",
            "antecedentesPersonales": "Intervención quirúrgica menor para extracción de quiste en 2022.",
            "diagnosticoPresuntivo": "Síndrome de fatiga crónica.",
            "diagnosticosDiferenciales": "Insuficiencia cardíaca, trastorno de ansiedad.",
            "examenFisicoGeneral": "Paciente con signos de fatiga y presión arterial elevada.",
            "examenFisicoEspecial": "Exploración cardíaca revela ruidos normales. No hay signos de insuficiencia cardíaca.",
            "propuestaBasicaDeConducta": "Tratamiento con estatinas y seguimiento de la presión arterial. Reevaluación si no hay mejora.",
            "tratamiento": "Atorvastatina 20mg cada noche. Control de presión arterial y dieta adecuada.",
            "createdAt": "2023-08-15T09:00:00Z",
            "updatedAt": "2023-08-18T10:20:00Z",
            "deletedAt": null,
            "idEspecialidad": 4,
            "nombreEspecialidad": "Cardiología",
            "idMedico": 16,
            "nombreMedico": "Laura Sánchez",
            "idPaciente": 4,
            "ciPropietario": "345678901",
            "pacientePropietario": "Carlos Rivera"
        },
        {
            "id": 5,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de gastritis crónica y alergias alimentarias. Reporta dolor abdominal recurrente.",
            "antecedentesFamiliares": "Hermano con problemas digestivos. Madre con hipertensión.",
            "antecedentesGinecoobstetricos": "Mujer, G1P0A0, sin embarazos previos.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, dieta irregular.",
            "antecedentesPatologicos": "Gastritis crónica desde hace años.",
            "antecedentesPersonales": "Sin cirugías previas.",
            "diagnosticoPresuntivo": "Exacerbación de gastritis crónica.",
            "diagnosticosDiferenciales": "Úlcera péptica, síndrome del intestino irritable.",
            "examenFisicoGeneral": "Paciente alerta y orientado. Dolor a la palpación abdominal.",
            "examenFisicoEspecial": "Exploración abdominal revela sensibilidad en el epigastrio.",
            "propuestaBasicaDeConducta": "Tratamiento con inhibidores de la bomba de protones y cambios en la dieta. Reevaluación si los síntomas persisten.",
            "tratamiento": "Omeprazol 20mg una vez al día. Evitar alimentos irritantes.",
            "createdAt": "2023-09-01T08:00:00Z",
            "updatedAt": "2023-09-07T09:30:00Z",
            "deletedAt": null,
            "idEspecialidad": 5,
            "nombreEspecialidad": "Gastroenterología",
            "idMedico": 18,
            "nombreMedico": "Javier Martínez",
            "idPaciente": 5,
            "ciPropietario": "456789012",
            "pacientePropietario": "Marta Castillo"
        },
        {
            "id": 6,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de depresión mayor y ansiedad. Reporta episodios de tristeza profunda y ansiedad.",
            "antecedentesFamiliares": "Madre con trastorno bipolar. Padre con depresión.",
            "antecedentesGinecoobstetricos": "Mujer, G1P1A0, sin complicaciones en el embarazo.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, poco ejercicio.",
            "antecedentesPatologicos": "Trastorno depresivo mayor tratado con medicación.",
            "antecedentesPersonales": "Sin intervenciones quirúrgicas previas.",
            "diagnosticoPresuntivo": "Trastorno depresivo mayor.",
            "diagnosticosDiferenciales": "Trastorno de ansiedad generalizada, trastorno bipolar.",
            "examenFisicoGeneral": "Paciente alerta pero con signos de desánimo. Afecto plano.",
            "examenFisicoEspecial": "Sin alteraciones físicas significativas.",
            "propuestaBasicaDeConducta": "Tratamiento con antidepresivos y terapia psicológica. Seguimiento frecuente.",
            "tratamiento": "Sertralina 50mg una vez al día. Psicoterapia semanal.",
            "createdAt": "2023-10-01T10:00:00Z",
            "updatedAt": "2023-10-05T11:45:00Z",
            "deletedAt": null,
            "idEspecialidad": 6,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 21,
            "nombreMedico": "Claudia Ortega",
            "idPaciente": 6,
            "ciPropietario": "567890123",
            "pacientePropietario": "Ana Torres"
        },
        {
            "id": 7,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de diabetes tipo 1 y neuropatía periférica. Reporta dolor y hormigueo en extremidades.",
            "antecedentesFamiliares": "Madre con diabetes tipo 2. Padre con problemas renales.",
            "antecedentesGinecoobstetricos": "Mujer, G2P2A0, embarazos sin complicaciones.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, realiza ejercicio moderado.",
            "antecedentesPatologicos": "Diabetes tipo 1 con neuropatía periférica.",
            "antecedentesPersonales": "Operada de pie diabético en 2020.",
            "diagnosticoPresuntivo": "Neuropatía diabética.",
            "diagnosticosDiferenciales": "Síndrome de Guillain-Barré, esclerosis múltiple.",
            "examenFisicoGeneral": "Paciente con signos de neuropatía periférica. Alerta y orientado.",
            "examenFisicoEspecial": "Exploración neurológica revela disminución de la sensibilidad en pies y manos.",
            "propuestaBasicaDeConducta": "Tratamiento con medicamentos para neuropatía y control estricto de glucemia. Seguimiento regular.",
            "tratamiento": "Gabapentina 300mg tres veces al día. Insulina ajustada según glucemia.",
            "createdAt": "2023-11-01T14:00:00Z",
            "updatedAt": "2023-11-05T15:30:00Z",
            "deletedAt": null,
            "idEspecialidad": 7,
            "nombreEspecialidad": "Neurología",
            "idMedico": 22,
            "nombreMedico": "Roberto Sánchez",
            "idPaciente": 7,
            "ciPropietario": "678901234",
            "pacientePropietario": "Luis Gómez"
        },
        {
            "id": 8,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de hipotiroidismo. Reporta fatiga y aumento de peso inexplicable.",
            "antecedentesFamiliares": "Madre con hipotiroidismo. Padre con enfermedad cardíaca.",
            "antecedentesGinecoobstetricos": "Mujer, G1P1A0, sin complicaciones en el embarazo.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, bajo nivel de actividad física.",
            "antecedentesPatologicos": "Hipotiroidismo tratado con medicación.",
            "antecedentesPersonales": "Sin cirugías previas.",
            "diagnosticoPresuntivo": "Hipotiroidismo no controlado.",
            "diagnosticosDiferenciales": "Síndrome de Cushing, depresión.",
            "examenFisicoGeneral": "Paciente con signos de fatiga y aumento de peso. Alerta y orientado.",
            "examenFisicoEspecial": "Examen tiroideo revela glándula tiroides normal. No hay nódulos palpables.",
            "propuestaBasicaDeConducta": "Ajuste de la medicación tiroidea y monitoreo de los niveles de TSH. Reevaluación si los síntomas persisten.",
            "tratamiento": "Levotiroxina 75mcg una vez al día. Control de niveles de TSH cada 6 semanas.",
            "createdAt": "2023-12-01T08:00:00Z",
            "updatedAt": "2023-12-05T09:45:00Z",
            "deletedAt": null,
            "idEspecialidad": 8,
            "nombreEspecialidad": "Endocrinología",
            "idMedico": 24,
            "nombreMedico": "Isabel Martínez",
            "idPaciente": 8,
            "ciPropietario": "789012345",
            "pacientePropietario": "Patricia Díaz"
        },
        {
            "id": 9,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de artritis reumatoide. Reporta dolor y rigidez en las articulaciones.",
            "antecedentesFamiliares": "Madre con artritis reumatoide. Padre con diabetes tipo 2.",
            "antecedentesGinecoobstetricos": "Mujer, G2P1A0, con embarazos sin complicaciones.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, realiza ejercicio suave.",
            "antecedentesPatologicos": "Artritis reumatoide en tratamiento.",
            "antecedentesPersonales": "Sin cirugías previas.",
            "diagnosticoPresuntivo": "Exacerbación de artritis reumatoide.",
            "diagnosticosDiferenciales": "Osteoartritis, lupus eritematoso sistémico.",
            "examenFisicoGeneral": "Paciente con signos de inflamación articular. Alerta y orientado.",
            "examenFisicoEspecial": "Exploración articular revela rigidez y dolor en múltiples articulaciones.",
            "propuestaBasicaDeConducta": "Ajuste del tratamiento con medicamentos antirreumáticos y terapia física. Reevaluación si los síntomas no mejoran.",
            "tratamiento": "Metotrexato 15mg una vez a la semana. Terapia física dos veces por semana.",
            "createdAt": "2024-01-01T10:00:00Z",
            "updatedAt": "2024-01-07T11:30:00Z",
            "deletedAt": null,
            "idEspecialidad": 9,
            "nombreEspecialidad": "Reumatología",
            "idMedico": 26,
            "nombreMedico": "Ana López",
            "idPaciente": 9,
            "ciPropietario": "890123456",
            "pacientePropietario": "Julieta Ruiz"
        },
        {
            "id": 10,
            "condicionesActualesEstadoSaludEnfermedad": "Paciente con antecedentes de epilepsia y migraña crónica. Reporta episodios frecuentes de convulsiones.",
            "antecedentesFamiliares": "Madre con migrañas frecuentes. Padre con epilepsia.",
            "antecedentesGinecoobstetricos": "Mujer, G3P2A1, sin complicaciones significativas.",
            "antecedentesNoPatologicos": "No fuma, consume alcohol ocasionalmente, realiza ejercicio regular.",
            "antecedentesPatologicos": "Epilepsia y migraña crónica en tratamiento.",
            "antecedentesPersonales": "Operada de una cirugía cerebral en 2018.",
            "diagnosticoPresuntivo": "Epilepsia no controlada.",
            "diagnosticosDiferenciales": "Trastorno convulsivo no epiléptico, cefalea en racimos.",
            "examenFisicoGeneral": "Paciente con signos de convulsiones frecuentes. Alerta y orientado.",
            "examenFisicoEspecial": "Exploración neurológica revela signos de actividad convulsiva reciente.",
            "propuestaBasicaDeConducta": "Reevaluación y ajuste del tratamiento antiepiléptico. Control de migrañas.",
            "tratamiento": "Lamotrigina 100mg dos veces al día. Topiramato 50mg una vez al día para migrañas.",
            "createdAt": "2024-02-01T12:00:00Z",
            "updatedAt": "2024-02-05T13:30:00Z",
            "deletedAt": null,
            "idEspecialidad": 10,
            "nombreEspecialidad": "Neurología",
            "idMedico": 28,
            "nombreMedico": "Carlos Pérez",
            "idPaciente": 10,
            "ciPropietario": "901234567",
            "pacientePropietario": "Elena Vargas"
        }                                                
    ];
}