export class NotasEvolucionDataDev {
    static listaNotasEvolucion: any[] = [
        {
            "id": 1,
            "cambiosPacienteResultadosTratamiento": "El paciente ha mostrado mejoría significativa después del cambio de medicación.",
            "createdAt": "2023-01-01T08:00:00Z",
            "updatedAt": "2023-01-10T10:00:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 1,
            "diagnosticoPresuntivo": "Ansiedad crónica",
            "idEspecialidad": 1,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 1,
            "nombreMedico": "Juan Arveloa",
            "idPaciente": 1,
            "ciPropietario": "098324789",
            "pacientePropietario": "Juan Tellez"
        },
        {
            "id": 2,
            "cambiosPacienteResultadosTratamiento": "Se ha observado una ligera mejoría en los síntomas después de ajustar la dosis del medicamento.",
            "createdAt": "2023-01-15T09:30:00Z",
            "updatedAt": "2023-01-20T11:45:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 2,
            "diagnosticoPresuntivo": "Depresión moderada",
            "idEspecialidad": 2,
            "nombreEspecialidad": "Psicología",
            "idMedico": 2,
            "nombreMedico": "Ana Martínez",
            "idPaciente": 2,
            "ciPropietario": "098765432",
            "pacientePropietario": "María López"
        },
        {
            "id": 3,
            "cambiosPacienteResultadosTratamiento": "El paciente reporta haber experimentado una reducción en los niveles de ansiedad.",
            "createdAt": "2023-02-01T07:00:00Z",
            "updatedAt": "2023-02-05T08:30:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 3,
            "diagnosticoPresuntivo": "Estrés postraumático",
            "idEspecialidad": 3,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 3,
            "nombreMedico": "Carlos Ramírez",
            "idPaciente": 1,
            "ciPropietario": "098324789",
            "pacientePropietario": "Juan Tellez"
        },
        {
            "id": 4,
            "cambiosPacienteResultadosTratamiento": "Se ha observado una estabilidad en el estado emocional del paciente tras el ajuste en la terapia.",
            "createdAt": "2023-02-10T08:15:00Z",
            "updatedAt": "2023-02-15T09:00:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 4,
            "diagnosticoPresuntivo": "Trastorno bipolar",
            "idEspecialidad": 1,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 4,
            "nombreMedico": "Laura Fernández",
            "idPaciente": 3,
            "ciPropietario": "567890123",
            "pacientePropietario": "Ana Ruiz"
        },
        {
            "id": 5,
            "cambiosPacienteResultadosTratamiento": "El paciente ha tenido una respuesta positiva al nuevo plan de tratamiento.",
            "createdAt": "2023-03-01T10:00:00Z",
            "updatedAt": "2023-03-05T11:30:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 5,
            "diagnosticoPresuntivo": "Esquizofrenia",
            "idEspecialidad": 4,
            "nombreEspecialidad": "Neurología",
            "idMedico": 5,
            "nombreMedico": "Pedro Gómez",
            "idPaciente": 1,
            "ciPropietario": "098324789",
            "pacientePropietario": "Juan Tellez"
        },
        {
            "id": 6,
            "cambiosPacienteResultadosTratamiento": "Se ha notado una disminución en los síntomas psicóticos tras ajustar el tratamiento.",
            "createdAt": "2023-03-10T08:30:00Z",
            "updatedAt": "2023-03-15T09:45:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 6,
            "diagnosticoPresuntivo": "Trastorno esquizofrénico",
            "idEspecialidad": 5,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 6,
            "nombreMedico": "Sofía Pérez",
            "idPaciente": 2,
            "ciPropietario": "789012345",
            "pacientePropietario": "Carlos Mendoza"
        },
        {
            "id": 7,
            "cambiosPacienteResultadosTratamiento": "El paciente ha mostrado una mejora en el control de los síntomas tras cambiar el medicamento.",
            "createdAt": "2023-04-01T07:45:00Z",
            "updatedAt": "2023-04-05T08:15:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 7,
            "diagnosticoPresuntivo": "Trastorno obsesivo-compulsivo",
            "idEspecialidad": 6,
            "nombreEspecialidad": "Psicología",
            "idMedico": 7,
            "nombreMedico": "David López",
            "idPaciente": 3,
            "ciPropietario": "890123456",
            "pacientePropietario": "Sara Martínez"
        },
        {
            "id": 8,
            "cambiosPacienteResultadosTratamiento": "La paciente ha tenido una notable mejora en la gestión de su ansiedad con el nuevo tratamiento.",
            "createdAt": "2023-04-10T09:00:00Z",
            "updatedAt": "2023-04-15T10:30:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 8,
            "diagnosticoPresuntivo": "Trastorno de ansiedad generalizada",
            "idEspecialidad": 2,
            "nombreEspecialidad": "Psicología",
            "idMedico": 8,
            "nombreMedico": "Elena Fernández",
            "idPaciente": 3,
            "ciPropietario": "901234567",
            "pacientePropietario": "Miguel Torres"
        },
        {
            "id": 9,
            "cambiosPacienteResultadosTratamiento": "Se ha observado una mejora en el estado general del paciente después de ajustar el tratamiento.",
            "createdAt": "2023-05-01T10:15:00Z",
            "updatedAt": "2023-05-05T11:00:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 9,
            "diagnosticoPresuntivo": "Trastorno depresivo persistente",
            "idEspecialidad": 3,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 9,
            "nombreMedico": "Ricardo Silva",
            "idPaciente": 2,
            "ciPropietario": "012345678",
            "pacientePropietario": "Laura Gómez"
        },
        {
            "id": 10,
            "cambiosPacienteResultadosTratamiento": "El paciente ha presentado una mejora en la calidad de vida tras el ajuste del tratamiento.",
            "createdAt": "2023-05-10T08:00:00Z",
            "updatedAt": "2023-05-15T09:15:00Z",
            "deletedAt": null,
            "idHistoriaClinica": 10,
            "diagnosticoPresuntivo": "Trastorno afectivo bipolar",
            "idEspecialidad": 1,
            "nombreEspecialidad": "Psiquiatría",
            "idMedico": 10,
            "nombreMedico": "Valeria Ruiz",
            "idPaciente": 1,
            "ciPropietario": "098324789",
            "pacientePropietario": "Juan Tellez"
        }
    ];
}